# Site settings
title: Rallycrossed.com
email: "Rallycrossed@christoc.com"
description: "Rallycrossed.com, Wildwood, Missouri"
url: https://Rallycrossed.com
baseurl: 
facebook_username: ""
twitter_username: "Rallycrossed"
instagram_username: ""
github_username:
deviantart_username: 
flickr_username: ""
discus_shortname: ""
share: false
google_analytics: G-QN6SVGPXYV


data_dir: _data

# Owner/author information
owner:
  name:   ChrisHammond
  avatar: ChrisHammond_sq_200.jpg
  favicon: favicon.ico
  info: Rallycrossed.com 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments:
  provider: false # disqus
  disqus:
    short_name: # "Rallycrossed"

# Internal nav
nav:
  - BLOG: "/blog/"
  - ABOUT: "/about/"
  

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:title/"
categories_path: "/blog/category/"
tags_path: "/blog/tag/"
# Plugins
plugins:
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",vendor]


# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/blog/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"



#jekyll_picture_tag

picture:
  suppress_warnings: true
  fast_build: true

# gallery page generation
defaults:
  - scope:
      type: galleryimage  # select all galleryimage pages
    values:
      layout: picture