title: Rallycrossed.com - Domain Name For Sale
email: rallycrossed@christoc.com
description: >- # this means to ignore newlines until "baseurl:"
  Do you have a use for Rallycrossed.com? Make an offer on this domain name, and see if we accept!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rallycrossed
github_username:  rallycrossed

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll_picture_tag

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
